basePath: /wellness
host: localhost
info:
  contact: {}
  description: Rokwire Content Building Block API Documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rokwire Wellness Building Block API
  version: 1.0.1
paths:
  /api/user/todo_categories:
    get:
      consumes:
      - application/json
      description: Retrieves all user todo categories
      operationId: GetUserTodoCategories
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    post:
      consumes:
      - application/json
      description: Creates a user todo category
      operationId: CreateUserTodoCategory
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
  /api/user/todo_categories/{id}:
    delete:
      description: Deletes a user todo category with the specified id
      operationId: DeleteUserTodoCategory
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    get:
      consumes:
      - application/json
      description: Retrieves a user todo category by id
      operationId: GetUserTodoCategory
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    put:
      consumes:
      - application/json
      description: Updates a user todo category with the specified id
      operationId: UpdateUserTodoCategory
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
  /api/user/todo_entries:
    get:
      consumes:
      - application/json
      description: Retrieves all user todo entries
      operationId: GetUserTodoEntries
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    post:
      consumes:
      - application/json
      description: Creates a user todo entry
      operationId: CreateUserTodoEntry
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
  /api/user/todo_entries/{id}:
    delete:
      description: Deletes a user todo entry with the specified id
      operationId: DeleteUserTodoEntry
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    get:
      consumes:
      - application/json
      description: Retrieves a user todo entry by id
      operationId: GetUserTodoEntry
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    put:
      consumes:
      - application/json
      description: Updates a user todo entry with the specified id
      operationId: UpdateUserTodoEntry
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
  /user/todo_entries/clear_completed_entries:
    delete:
      description: Deletes all completed user todo entries
      operationId: DeleteCompletedUserTodoEntry
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
  /version:
    get:
      description: Gives the service version.
      operationId: Version
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      tags:
      - Client
schemes:
- https
securityDefinitions:
  AdminGroupAuth:
    in: header
    name: GROUP
    type: apiKey
  AdminUserAuth:
    in: header (add Bearer prefix to the Authorization value)
    name: Authorization
    type: apiKey
  UserAuth:
    in: header (add Bearer prefix to the Authorization value)
    name: Authorization
    type: apiKey
swagger: "2.0"
